### ISSUE TITLE
Feature requests 

### ISSUE THREAD

**Issue by Sentdex** [Fuchsiaff/PyPad#21]
Things I would want to see in order to make this my primary editor:

1. Tabs and project opening (what you're doing now.) -- **Done**
2. Auto indent working properly -- **Done**
3. Pep8 hinting (EXCEPT FOR the <78 chars req, or make it customize-able. The 78 char limit is just annoying.)
4. Auto complete/suggestions. If I start typing a method or var, make suggestions that I can use arrow keys and tab to select, like I can in sublime.
5. Ability to run the script from pypad itself, and see console output. Needs a shortcut to run it. -- **Done**
6. Ability to run in interactive mode. I miss the ability to run a script in IDLE, and then continue coding live in the console part. I wish Sublime would let me do that. It doesnt need to always work this way, maybe 2 run options. -- **Done**
7. Document search, and "search all." Should include options like search for whole word, sub string, and regex search for both that specific doc search and when searching across all documents.
8. Code diff. I'd really like to not need multiple programs to see differences between 2 scripts. 

Probably more, I'll add if I think of any others.

**Comment by Fuchsiaff** [comment]
Tabs and project opening (what you're doing now.) _DONE_
    Auto indent working properly _DONE_
    Pep8 hinting (EXCEPT FOR the <78 chars req, or make it customize-able. The 78 char limit is just annoying.)
    Auto complete/suggestions. If I start typing a method or var, make suggestions that I can use arrow keys and tab to select, like I can in sublime.
    Ability to run the script from pypad itself, and see console output. Needs a shortcut to run it. _Kind of DONE__ (Needs improvement)
    Ability to run in interactive mode. I miss the ability to run a script in IDLE, and then continue coding live in the console part. I wish Sublime would let me do that. It doesnt need to always work this way, maybe 2 run options.
    Document search, and "search all." Should include options like search for whole word, sub string, and regex search for both that specific doc search and when searching across all documents.
    Code diff. I'd really like to not need multiple programs to see differences between 2 scripts.

**Comment by wilfred-kun** [comment]
Bouncing off of nr. 6. Integrated terminal like Atom's platform-ide-terminal would be a great addition.

**Comment by Fuchsiaff** [comment]
@wilfred-kun if you could provide a gif on how it works, I would appreciate that!

**Comment by wilfred-kun** [comment]
@Fuchsiaff There are a few examples on [this page](https://atom.io/packages/platformio-ide-terminal).

**Comment by abhinuvpitale** [comment]
Asking whether to save the file before exit? That should be a mandatory feature!

**Comment by Fuchsiaff** [comment]
@abhinuvpitale I forgot about that feature, I added it!

**Comment by abhinuvpitale** [comment]
@Fuchsiaff is anybody working on it? If not, I'd like to try to get it done!

**Comment by Fuchsiaff** [comment]
@abhinuvpitale I already implemented it

**Comment by abhinuvpitale** [comment]
Another feature that I'd like is to see if the file has been edited or not!
Usually showed by **main.py***

**Comment by Fuchsiaff** [comment]
@abhinuvpitale Added, it looks like this: https://gyazo.com/20d827b44bd0b58460dba7bb94837ae6

**Comment by abhinuvpitale** [comment]
@Fuchsiaff  anything I can help with?

**Comment by Fuchsiaff** [comment]
@abhinuvpitale You could work on improving the syntax highlighting, or code difference.

**Comment by JTopanotti** [comment]
I could probably work on the code-diff
