### ISSUE TITLE
`"'''"` parses as a multiline string

### ISSUE THREAD

**Issue by henry232323** [Fuchsiaff/PyPad#26]

**Comment by henry232323** [comment]
That is to say, even if the """ or ''' is between quotes and thus not opening a multiline string, it not is parsed as such

**Comment by Fuchsiaff** [comment]
I am aware of this problem and I will be implementing a new highlighting system soon which should fix it!

**Comment by AnonymousDapper** [comment]
Pygments and/or QScintilla work well with this.

**Comment by Fuchsiaff** [comment]
Fixed
