### ISSUE TITLE
Incorrect install.sh file

### ISSUE THREAD

**Issue by abhinuvpitale** [Fuchsiaff/PyPad#44]
I think a wrong and incomplete file is uploaded in the master branch.

**Comment by xIdyllic** [comment]
install.sh file is correct, and does work - I'm going to assume it doesn't work because your pypad path already exists. If it doesn't, regardless it doesn't matter since setup.py will be implemented over this. install.sh files aren't the way to go for this project especially in Python.

**Comment by abhinuvpitale** [comment]
Oh right, I thought it was meant to do more than just clone the files. I can see that the only things that are needed are in the repo itself.
