### ISSUE TITLE
Need help to implement line and col display on status bar

### ISSUE THREAD

**Issue by yiyite** [Fuchsiaff/PyPad#49]
Need some help to implement line and col display on status bar while navigating in the editor 
using cursorPositionChanged() 

Any help will be greatly appreciated.

Thanks

Leslie Lespes

l.lespes@axion.ca

**Comment by Fuchsiaff** [comment]
Thank you for the suggestion, I implemented it!
![image](https://user-images.githubusercontent.com/31344416/50641680-66af5b00-0f71-11e9-815d-c7174578f65a.png)
This is how it looks like

**Comment by yiyite** [comment]
Thank you very much. Is it implemented in the version of gihub repository ???

 

Have a good day and happy new year.

 

Leslie Lespes

 

De : Fuchsiaff [mailto:notifications@github.com] 
Envoyé : Thursday, January 3, 2019 9:06 AM
À : Fuchsiaff/PyPad
Cc : yiyite; Author
Objet : Re: [Fuchsiaff/PyPad] Need help to implement line and col display on status bar (#49)

 

Closed #49 <https://github.com/Fuchsiaff/PyPad/issues/49> .

**Comment by Fuchsiaff** [comment]
Yes, it's implemented in the current version of the repo

**Comment by yiyite** [comment]
I noticed that the philosophy of the application has changed. You created a status bar for the tab widget. I was trying to use the Main status bar to display Line and Col. I guess this new layout was the only way to make the implementation possible.

 

Thanks



Leslie

 

De : Fuchsiaff [mailto:notifications@github.com] 
Envoyé : Thursday, January 3, 2019 10:47 AM
À : Fuchsiaff/PyPad
Cc : yiyite; Author
Objet : Re: [Fuchsiaff/PyPad] Need help to implement line and col display on status bar (#49)

 

Yes, it's implemented in the current version of the repo

**Comment by Fuchsiaff** [comment]
Yeah, my first implementation used the status bar of the Main class but that only updated the statustip when you "unfocused" from the window so that was unacceptable
